<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PasteStatus;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PasteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PasteRepository extends EntityRepository
{
    public function findAllPublic(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->andWhere('p.key IS NOT NULL')
            ->andWhere('p.status = :status')
            ->setParameter('status', PasteStatus::ACTIVE)
            ->andWhere('p.user = :user_id')
            ->setParameter('user_id', $user)
        ;

        return $qb->getQuery()->getResult();
    }
}
