# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        bzbb:
            entity:
                class: AppBundle:User
                property: bzid

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            guard:
                authenticators:
                    - allejo\BZBBAuthenticationBundle\Security\BZBBAuthenticator
            logout_on_user_change: true
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/edit, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/new, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, role: IS_AUTHENTICATED_FULLY }
